### ISSUE TITLE
function cloudformation json의 누락된 부분 발견

### ISSUE THREAD

**Issue by geoseong** [marsinearth/amplify-photo-albums#1]
https://github.com/marsinearth/amplify-photo-albums/blob/9ec20840d5084e4e0d61e14ee019a78fe5e473a8/amplify/backend/function/workshopphotoprocessor/workshopphotoprocessor-cloudformation-template.json#L17 바로 밑 줄에다가 이 코드를 함 추가해 보세요. 제 로컬에는 있는데 이 리포에는 발견이 안되어서요.
```
"Metadata": {
  "aws:asset:path": "./src",
  "aws:asset:property": "Code"
},
```

**Comment by marsinearth** [comment]
안되요 ㅜㅜ 그거 전체 복붙하니까 없어졌던건데..

**Comment by geoseong** [comment]
@marsinearth 아하.. 한번 만나서 보실래여? ㅋ 가이드페이지에 복붙하는 내용은 조금 누락된 내용이 있는걸 발견했네요
